services:
  postgres:
    image: postgres:17-alpine
    container_name: hanura-postgres
    restart: unless-stopped

    env_file:
      - .env.local

    ports:
      - "5434:5432"

    volumes:
      - hanura_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  hanura_postgres_data:
