/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1AuthLoginRouteImport } from './routes/api/v1/auth/login'
import { Route as ApiV1AuthLogoutRouteImport } from './routes/api/v1/auth/logout'
import { Route as ApiV1AuthSessionRouteImport } from './routes/api/v1/auth/session'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLoginRoute = ApiV1AuthLoginRouteImport.update({
  id: '/api/v1/auth/login',
  path: '/api/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLogoutRoute = ApiV1AuthLogoutRouteImport.update({
  id: '/api/v1/auth/logout',
  path: '/api/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthSessionRoute = ApiV1AuthSessionRouteImport.update({
  id: '/api/v1/auth/session',
  path: '/api/v1/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/session': typeof ApiV1AuthSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/session': typeof ApiV1AuthSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/session': typeof ApiV1AuthSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/session'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/api/auth/$'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1AuthLoginRoute: typeof ApiV1AuthLoginRoute
  ApiV1AuthLogoutRoute: typeof ApiV1AuthLogoutRoute
  ApiV1AuthSessionRoute: typeof ApiV1AuthSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/login': {
      id: '/api/v1/auth/login'
      path: '/api/v1/auth/login'
      fullPath: '/api/v1/auth/login'
      preLoaderRoute: typeof ApiV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/logout': {
      id: '/api/v1/auth/logout'
      path: '/api/v1/auth/logout'
      fullPath: '/api/v1/auth/logout'
      preLoaderRoute: typeof ApiV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/session': {
      id: '/api/v1/auth/session'
      path: '/api/v1/auth/session'
      fullPath: '/api/v1/auth/session'
      preLoaderRoute: typeof ApiV1AuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1AuthLoginRoute: ApiV1AuthLoginRoute,
  ApiV1AuthLogoutRoute: ApiV1AuthLogoutRoute,
  ApiV1AuthSessionRoute: ApiV1AuthSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
