/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated.members'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1DashboardRouteImport } from './routes/api/v1/dashboard'
import { Route as ApiV1MembersRouteImport } from './routes/api/v1/members'
import { Route as ApiV1AuthLoginRouteImport } from './routes/api/v1/auth/login'
import { Route as ApiV1AuthLogoutRouteImport } from './routes/api/v1/auth/logout'
import { Route as ApiV1AuthSessionRouteImport } from './routes/api/v1/auth/session'
import { Route as ApiV1MembersIdRouteImport } from './routes/api/v1/members/$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DashboardRoute = ApiV1DashboardRouteImport.update({
  id: '/api/v1/dashboard',
  path: '/api/v1/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MembersRoute = ApiV1MembersRouteImport.update({
  id: '/api/v1/members',
  path: '/api/v1/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLoginRoute = ApiV1AuthLoginRouteImport.update({
  id: '/api/v1/auth/login',
  path: '/api/v1/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthLogoutRoute = ApiV1AuthLogoutRouteImport.update({
  id: '/api/v1/auth/logout',
  path: '/api/v1/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1AuthSessionRoute = ApiV1AuthSessionRouteImport.update({
  id: '/api/v1/auth/session',
  path: '/api/v1/auth/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1MembersIdRoute = ApiV1MembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1MembersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/members': typeof AuthenticatedMembersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/dashboard': typeof ApiV1DashboardRoute
  '/api/v1/members': typeof ApiV1MembersRouteWithChildren
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/session': typeof ApiV1AuthSessionRoute
  '/api/v1/members/$id': typeof ApiV1MembersIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/members': typeof AuthenticatedMembersRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/dashboard': typeof ApiV1DashboardRoute
  '/api/v1/members': typeof ApiV1MembersRouteWithChildren
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/session': typeof ApiV1AuthSessionRoute
  '/api/v1/members/$id': typeof ApiV1MembersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/v1/dashboard': typeof ApiV1DashboardRoute
  '/api/v1/members': typeof ApiV1MembersRouteWithChildren
  '/api/v1/auth/login': typeof ApiV1AuthLoginRoute
  '/api/v1/auth/logout': typeof ApiV1AuthLogoutRoute
  '/api/v1/auth/session': typeof ApiV1AuthSessionRoute
  '/api/v1/members/$id': typeof ApiV1MembersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/members'
    | '/api/auth/$'
    | '/api/v1/dashboard'
    | '/api/v1/members'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/session'
    | '/api/v1/members/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/members'
    | '/'
    | '/api/auth/$'
    | '/api/v1/dashboard'
    | '/api/v1/members'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/session'
    | '/api/v1/members/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/members'
    | '/_authenticated/'
    | '/api/auth/$'
    | '/api/v1/dashboard'
    | '/api/v1/members'
    | '/api/v1/auth/login'
    | '/api/v1/auth/logout'
    | '/api/v1/auth/session'
    | '/api/v1/members/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1DashboardRoute: typeof ApiV1DashboardRoute
  ApiV1MembersRoute: typeof ApiV1MembersRouteWithChildren
  ApiV1AuthLoginRoute: typeof ApiV1AuthLoginRoute
  ApiV1AuthLogoutRoute: typeof ApiV1AuthLogoutRoute
  ApiV1AuthSessionRoute: typeof ApiV1AuthSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/dashboard': {
      id: '/api/v1/dashboard'
      path: '/api/v1/dashboard'
      fullPath: '/api/v1/dashboard'
      preLoaderRoute: typeof ApiV1DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/members': {
      id: '/api/v1/members'
      path: '/api/v1/members'
      fullPath: '/api/v1/members'
      preLoaderRoute: typeof ApiV1MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/login': {
      id: '/api/v1/auth/login'
      path: '/api/v1/auth/login'
      fullPath: '/api/v1/auth/login'
      preLoaderRoute: typeof ApiV1AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/logout': {
      id: '/api/v1/auth/logout'
      path: '/api/v1/auth/logout'
      fullPath: '/api/v1/auth/logout'
      preLoaderRoute: typeof ApiV1AuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/auth/session': {
      id: '/api/v1/auth/session'
      path: '/api/v1/auth/session'
      fullPath: '/api/v1/auth/session'
      preLoaderRoute: typeof ApiV1AuthSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/members/$id': {
      id: '/api/v1/members/$id'
      path: '/$id'
      fullPath: '/api/v1/members/$id'
      preLoaderRoute: typeof ApiV1MembersIdRouteImport
      parentRoute: typeof ApiV1MembersRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ApiV1MembersRouteChildren {
  ApiV1MembersIdRoute: typeof ApiV1MembersIdRoute
}

const ApiV1MembersRouteChildren: ApiV1MembersRouteChildren = {
  ApiV1MembersIdRoute: ApiV1MembersIdRoute,
}

const ApiV1MembersRouteWithChildren = ApiV1MembersRoute._addFileChildren(
  ApiV1MembersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1DashboardRoute: ApiV1DashboardRoute,
  ApiV1MembersRoute: ApiV1MembersRouteWithChildren,
  ApiV1AuthLoginRoute: ApiV1AuthLoginRoute,
  ApiV1AuthLogoutRoute: ApiV1AuthLogoutRoute,
  ApiV1AuthSessionRoute: ApiV1AuthSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
